trigger: none

pool: 
-agent_pool

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello India"'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World kaieshioo"

