trigger: none

pool: my_agent

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
    backendServiceArm: 'new_svc'
    backendAzureRmOverrideSubscriptionID: 'ca2d764d-6af0-4ecc-8eaf-76bd3b666806'
    backendAzureRmStorageAccountName: 'storagedev12'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
